[build]
  command = "scully:build:prod"
  functions = "netlify/functions"
  publish = "dist/static"

[build.environment]
  NODE_VERSION = "14.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

